cloud_id                 = "b1gq2268nliamvaqve55"
folder_id                = "b1g7ofc9eqj0bplnnief"
zone                     = "ru-central1-a"
public_key_path          = "~/.ssh/appuser.pub"
subnet_id                = "e9bbsris6d2huf7jv1pe"
service_account_key_file = "~/.ssh/key.json"
private_key_path         = "~/.ssh/appuser"
image_id                 = "fd87va5cc00gaq2f5qfb"
