apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
    app: elasticsearch-logging
spec:
  selector:
    k8s-app: elasticsearch-logging
    app: elasticsearch-logging
  ports:
  - port: 9200
    protocol: TCP
    # targetPort: rest
  - port: 9300
    name: inter-node
    # targetPort: db
    # targetPort: 9200
