---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    # kubernetes.io/ingress.provider: nginx
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host | default .Release.Name }}
      secretName: gitlab-gitlab-tls
  rules:
  - host: {{ .Values.ingress.host | default .Release.Name }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "ui.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
