---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "prometheus.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host | default .Release.Name }}
    http:
      paths:
      - path: /graph
        pathType: ImplementationSpecific
        backend:
          serviceName: {{ template "prometheus.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
