---
apiVersion: v1
data:
  auth: Zm9vOiRhcHIxJE5DRzJ5anVFJHJnWW9MZGpRL3Bmb0dEVE8zdTFlVjEK
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:auth: {}
      f:type: {}
    manager: kubectl
    operation: Update
  name: basic-auth
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "prometheus.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
spec:
  rules:
  - host: prometheus.{{ .Values.ingress.host | default .Release.Name }}
    http:
      paths:
      - path: /
      # - path: /prometheus/
        # pathType: ImplementationSpecific
        backend:
          serviceName: {{ template "prometheus.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
