---
apiVersion: v1
data:
  auth: Zm9vOiRhcHIxJE5DRzJ5anVFJHJnWW9MZGpRL3Bmb0dEVE8zdTFlVjEK
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:auth: {}
      f:type: {}
    manager: kubectl
    operation: Update
  name: basic-auth
type: Opaque
