---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    app: search_engine
    component: prometheus
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: search_engine
      component: prometheus
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: search_engine
        component: prometheus
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: prometheus
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: prometheus
          protocol: TCP
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
